import type { AiTutorTheme } from '../../types/ai-tutor';

export const aiTutorThemes: Record<string, AiTutorTheme> = {
  foundations: {
    accent: 'text-blue-600',
    buttonBg: 'bg-blue-600',
    buttonHoverBg: 'hover:bg-blue-700',
    headerBg: 'bg-blue-600',
    userBubbleBg: 'bg-blue-600',
    lightBg: 'bg-blue-50',
    borderColor: 'border-blue-200',
    iconColor: 'text-blue-600',
    focusRing: 'focus:ring-blue-500',
  },
  compliance: {
    accent: 'text-slate-600',
    buttonBg: 'bg-slate-600',
    buttonHoverBg: 'hover:bg-slate-700',
    headerBg: 'bg-slate-600',
    userBubbleBg: 'bg-slate-600',
    lightBg: 'bg-slate-50',
    borderColor: 'border-slate-200',
    iconColor: 'text-slate-600',
    focusRing: 'focus:ring-slate-500',
  },
  insurance: {
    accent: 'text-emerald-600',
    buttonBg: 'bg-emerald-600',
    buttonHoverBg: 'hover:bg-emerald-700',
    headerBg: 'bg-emerald-600',
    userBubbleBg: 'bg-emerald-600',
    lightBg: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    iconColor: 'text-emerald-600',
    focusRing: 'focus:ring-emerald-500',
  },
  workflows: {
    accent: 'text-amber-600',
    buttonBg: 'bg-amber-600',
    buttonHoverBg: 'hover:bg-amber-700',
    headerBg: 'bg-amber-600',
    userBubbleBg: 'bg-amber-600',
    lightBg: 'bg-amber-50',
    borderColor: 'border-amber-200',
    iconColor: 'text-amber-600',
    focusRing: 'focus:ring-amber-500',
  },
  administration: {
    accent: 'text-teal-600',
    buttonBg: 'bg-teal-600',
    buttonHoverBg: 'hover:bg-teal-700',
    headerBg: 'bg-teal-600',
    userBubbleBg: 'bg-teal-600',
    lightBg: 'bg-teal-50',
    borderColor: 'border-teal-200',
    iconColor: 'text-teal-600',
    focusRing: 'focus:ring-teal-500',
  },
  terminology: {
    accent: 'text-indigo-600',
    buttonBg: 'bg-indigo-600',
    buttonHoverBg: 'hover:bg-indigo-700',
    headerBg: 'bg-indigo-600',
    userBubbleBg: 'bg-indigo-600',
    lightBg: 'bg-indigo-50',
    borderColor: 'border-indigo-200',
    iconColor: 'text-indigo-600',
    focusRing: 'focus:ring-indigo-500',
  },
  practice: {
    accent: 'text-rose-600',
    buttonBg: 'bg-rose-600',
    buttonHoverBg: 'hover:bg-rose-700',
    headerBg: 'bg-rose-600',
    userBubbleBg: 'bg-rose-600',
    lightBg: 'bg-rose-50',
    borderColor: 'border-rose-200',
    iconColor: 'text-rose-600',
    focusRing: 'focus:ring-rose-500',
  },
};

export const defaultSuggestedQuestions: Record<string, string[]> = {
  workflows: [
    'Walk me through new patient registration',
    'What forms does a Medicare patient need?',
    'How should I handle a no-show?',
    'Explain the check-in process',
  ],
  insurance: [
    'How do I verify insurance eligibility?',
    'Explain copays vs deductibles vs coinsurance',
    'How do I read an insurance card?',
    'What is prior authorization?',
  ],
  compliance: [
    'What is HIPAA and why does it matter?',
    'What counts as PHI?',
    'Explain the Minimum Necessary Rule',
    'What are common HIPAA violations?',
  ],
  foundations: [
    'What does front office staff do?',
    'Explain acute vs ambulatory care',
    'What skills do I need for healthcare admin?',
    'What is the typical front desk workflow?',
  ],
  terminology: [
    'How do medical terms get built?',
    'What are common prefixes I should know?',
    'Explain common abbreviations like PRN and BID',
    'Help me practice decoding a medical term',
  ],
  administration: [
    'Walk me through opening procedures',
    'What are end-of-day closing tasks?',
    'How do I handle office supply management?',
    'Explain cash drawer reconciliation',
  ],
  practice: [
    'Give me a patient check-in scenario to practice',
    'Quiz me on insurance terms',
    'Help me practice phone etiquette',
    'Test my knowledge of HIPAA rules',
  ],
};
